import {
  Utensils, Bus, ShoppingBag, Film, Receipt, HeartPulse, Book,
  Briefcase, TrendingUp, Wifi, Wallet, MoreHorizontal, CreditCard,
  Wine, Coffee, Cake, Percent, type LucideIcon, HelpCircle, Activity,
  Baby, Camera, Car, DollarSign, Dumbbell, Gamepad2, Gift, GraduationCap,
  Home, Monitor, Music, Plane, Scissors, Shirt, Smartphone, Truck, Users, Zap
} from "lucide-react"

export const ICON_MAP: Record<string, LucideIcon> = {
  utensils: Utensils, 
  bus: Bus, 
  "shopping-bag": ShoppingBag, 
  film: Film,
  receipt: Receipt, 
  "heart-pulse": HeartPulse, 
  book: Book, 
  briefcase: Briefcase,
  "trending-up": TrendingUp, 
  wifi: Wifi, 
  wallet: Wallet, 
  "more-horizontal": MoreHorizontal,
  "credit-card": CreditCard, 
  wine: Wine, 
  coffee: Coffee, 
  cake: Cake, 
  percent: Percent,
  
  // Extended icons
  activity: Activity,
  baby: Baby,
  camera: Camera,
  car: Car,
  "dollar-sign": DollarSign,
  dumbbell: Dumbbell,
  "gamepad-2": Gamepad2,
  gift: Gift,
  "graduation-cap": GraduationCap,
  home: Home,
  monitor: Monitor,
  music: Music,
  plane: Plane,
  scissors: Scissors,
  shirt: Shirt,
  smartphone: Smartphone,
  truck: Truck,
  users: Users,
  zap: Zap,
  "help-circle": HelpCircle,
}
