-- ==========================================
-- SCHEMA DATABASE N.E.X.A (Supabase PostgreSQL)
-- ==========================================

-- 1. Table untuk Memori Kontekstual (Agar AI bisa mengingat chat sebelumnya)
CREATE TABLE IF NOT EXISTS nexa_chat_memories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT NOT NULL, -- Berisi 'user' (Anda) atau 'nexa'
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Table untuk Sistem Deduplikasi Keuangan (Mencegah Pencatatan Ganda dari Tasker/Telegram)
CREATE TABLE IF NOT EXISTS nexa_finance_dedup (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  composite_key TEXT NOT NULL, -- Format rahasia: "Nominal_Merchant"
  transaction_time TIMESTAMP WITH TIME ZONE NOT NULL,
  source TEXT NOT NULL, -- Jalur masuk: 'TELEGRAM_MANUAL' atau 'TASKER_LIVIN'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Membuat Indexing (Logika Tingkat Tinggi untuk mempercepat pencarian data pada tabel yang besar)
CREATE INDEX IF NOT EXISTS idx_finance_dedup_time ON nexa_finance_dedup(transaction_time);
CREATE INDEX IF NOT EXISTS idx_finance_dedup_key ON nexa_finance_dedup(composite_key);

-- 3. Table untuk Gudang Ide Mentah (Arsip mentah dari ekosistem 2nd Brain)
CREATE TABLE IF NOT EXISTS nexa_2nd_brain (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  content TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
